### ISSUE TITLE
Which library should replace the Cairo toy text API for text layout and rendering?

### ISSUE THREAD

**Issue by rylev** [linebender/piet#10]
For simplicity, the back-end currently uses the toy text API in Cairo. Essentially, this means there is no shaping, so complex scripts won't render correctly at all, and Latin will be missing kerning, ligatures, and other refinements. According to the docs, "Any serious application should avoid them."

Fairly soon, @raphlinus  hopes to have some type of higher-level text in place. One possibility is pango. From what @raphlinus can tell, this should work well on Linux, but since it has a non-optional glib dependency, it might be non-trivial to get it building portably. It's also not clear how well this approach handles discovering system fonts.

Another possibility is to use HarfBuzz more directly, using the rust-harfbuzz bindings. This will require more work for font discovery and selection but has the possibility to be considerably more native. A good Rust-native candidate for system font discovery is font-kit.

A third possibility is to adapt libTXT from Flutter. This is a state of the art text layout library, with considerable investment in making it work well on mobile. However, it is in C++ and thus at the very least will need nontrivial work to make good Rust bindings.

**Comment by SimonSapin** [comment]
https://github.com/linebender/piet/issues/8 has some overlap with this.

**Comment by raphlinus** [comment]
I'm basically doing the second option here. As I wrote in #8, here is a [roadmap](https://docs.google.com/document/d/1aw41q_izail-p99mN8dHrJeh9tMQ-Pldi54W6m7MHU8/edit?usp=sharing) for that project.

**Comment by JAicewizard** [comment]
Isnt this already implemented now? Piet-cairo now uses pango for text.

**Comment by cmyr** [comment]
Thanks!
