### ISSUE TITLE
piet_common API to create an image file?

### ISSUE THREAD

**Issue by cmyr** [linebender/piet#128]
Playing around with testing, and have wanted to do something that I don't see an obvious API for: basically I would like to use the `piet_common` types (`Device`, `BitmapTarget` etc) to do some drawing, but then I would like to save the result to disk. I won't mind if the format of the image differs per-backend (although I suppose this isn't ideal) but I would like to be able to easily dump the current buffer in a way that lets me go take a look at it with an image viewer. Is this possible somehow?

**Comment by raphlinus** [comment]
We currently have [image](https://crates.io/crates/image) as a dev-dependency in piet. This is a very heavyweight crate (at least by default, where lots of image codecs are turned on, and there are more dependencies for those). I would be open to changing that to png and moving the save function from the examples to the main library, as that seems like generally very useful functionality and a light enough dependency we can tolerate it.

**Comment by Dmitry-Borodin** [comment]
working on it

**Comment by Dmitry-Borodin** [comment]
Changed "image" crate to "png" crate dependency, now instead of 1.5-2Mb, we have ~200kb dependency according to lib.rs
Should I now implement saving to file functionality as public function of BitmapTarget for cairo backend?
