### ISSUE TITLE
Windows CI

### ISSUE THREAD

**Issue by rylev** [linebender/piet#14]
Currently the CI only runs on Linux. We need to also run on macOS and Windows. There are a few small challenges to this:

* Linux and macOS cannot build `piet-direct2d`. The .travis.yml script needs to ensure that building of `piet-direct2d` doesn't happen on non-Windows OSs.
* Travis Windows and macOS don't have cairo installed and this is needed to run. macOS returns the following error: ```Package cairo was not found in the pkg-config search path.
Perhaps you should add the directory containing `cairo.pc'
to the PKG_CONFIG_PATH environment variable
No package 'cairo' found```

**Comment by SimonSapin** [comment]
`brew install cairo` might work on macOS?

**Comment by rylev** [comment]
macOS is done. I will update the README to reflect that one only needs to install cairo.

**Comment by rylev** [comment]
Travis's Windows support is fairly new so we might run into issues. 

Looking into it, the way that GTK and the GTK-rs project recommend installing GTK (and subsequently cairo) is through [MSYS2](http://gtk-rs.org/docs/requirements.html) and using pacman. This shell is not installed on the Travis Windows machines. It seems [someone has tried to install MSYS2 using chocolatey but they failed](https://travis-ci.community/t/how-do-i-use-mingw-and-msys2-shells/1787) to be able to switch to the shell from the bash shell that Travis uses.

Cairo has [release binaries](https://www.cairographics.org/releases/) which we could also try to use.

**Comment by rylev** [comment]
Fixed by #23
