### ISSUE TITLE
Color::as_rgba does not take self param?

### ISSUE THREAD

**Issue by cmyr** [linebender/piet#180]
Is this an oversight or am I missing something?

```rust
/// Convert a color value to four f64 values, each in the range 0.0 to 1.0.
    pub fn as_rgba(rgba: &Color) -> (f64, f64, f64, f64) {
        let rgba = rgba.as_rgba_u32();
        (
            (rgba >> 24) as f64 / 255.0,
            ((rgba >> 16) & 255) as f64 / 255.0,
            ((rgba >> 8) & 255) as f64 / 255.0,
            (rgba & 255) as f64 / 255.0,
        )
    }
```

This requires you to write `Color::as_rgba(&my_color)` instead of `my_color.as_rbga()`.

**Comment by raphlinus** [comment]
I believe it is an oversight and should be switched to `self`. Doing a quick look, the source of this is #159, where it was originally `From` but was switch to an `as_` version. @futurepaul would probably be able to say for sure, but I'm comfortable with changing it.

**Comment by futurepaul** [comment]
That's exactly what happened, sorry for the oversight!
