### ISSUE TITLE
piet-web: Stroked Text

### ISSUE THREAD

**Issue by bdon** [linebender/piet#206]
This is a freebie for WebRender:

https://github.com/linebender/piet/compare/master...bdon:stroke_text

 Based on the Zulip thread this seems like a reasonable feature to have universally, but is non-trivial for other targets. Should I try to make this limited to web for now or add a no-op implementation for other targets?

**Comment by cmyr** [comment]
good question. It's definitely tricky in some places. I think it's reasonable to add just to the web context? I could also imagine us adding extension traits for behaviours that are only available on some backends, like `StrokeTextExt`, but that might be overly fancy for now.
