### ISSUE TITLE
`Send` for `Device`?

### ISSUE THREAD

**Issue by jneem** [linebender/piet#211]
Can `Device` be `Send`? On Windows, it currently isn't, although the [API docs](https://docs.microsoft.com/en-us/windows/win32/direct3d11/overviews-direct3d-11-render-multi-thread-intro) suggest that `D3D11Device` is Sync and `D3D11DeviceContext` is Send, and [these docs](https://docs.microsoft.com/en-us/windows/win32/direct2d/multi-threaded-direct2d-apps) suggest that everything `d2d` is Sync. I couldn't find anything about DirectWrite, but probably if something needs to be called from a particular thread, then it would be documented?

Edit: if `Device` can't be made Send, maybe it should be !Send on all platforms? Otherwise it's a portability footgun.

**Comment by raphlinus** [comment]
Super good questions. I agree that ideally this is consistent across platforms, but figuring out what that should be involves researching the thread safety of other platforms, and potentially putting in some extra mechanism to enforce thread safety.

**Comment by jneem** [comment]
While I have no knowledge of future (or even in-progress) backends, the current status is that only on windows is `Device` non-send.

**Comment by cmyr** [comment]
I think that yes, given the limited scope of `Device` we can reasonably assume that it can be `Send`. If for complicated reasons this is impossible for some future backend we can reconsider, but I find that hard to envision.
