### ISSUE TITLE
Copying pixels out of a BitmapTarget?

### ISSUE THREAD

**Issue by jneem** [linebender/piet#212]
The only current way to get pixel data out of a `BitmapTarget` involves consuming it. Would you accept a patch that adds a function with a signature like this?
```rust
impl BitmapTarget {
  fn copy_raw_pixels(&self, fmt: ImageFormat, buf: &mut [u8]) -> Result<usize, Error>
}
```
It would return the number of bytes written, or an error if the buf isn't big enough.

My use-case for this is encoding video: I want to render to a `BitmapTarget` and then pass the data to gstreamer for encoding. My data is mostly unchanged from frame to frame; I want to reuse the bitmap so that I only need to render the changed parts.

**Comment by raphlinus** [comment]
Yes, this is reasonable, as long as it works reliably across back-ends. I understand the usecase.
