### ISSUE TITLE
Cairo backend extremely slow text hit test 

### ISSUE THREAD

**Issue by ForLoveOfCats** [linebender/piet#222]
On wimpy system the following amount of text is enough to make dragging selection slow enough to lock up the UI for seconds at a time (due to performing a hit test on every mouse movement event).
![image](https://user-images.githubusercontent.com/30666851/86054117-91278a80-ba27-11ea-8ae9-2b5c8320723d.png)

Here is a `perf` recording showing that the issue resides within `piet_cairo`'s hit test functionality
![image](https://user-images.githubusercontent.com/30666851/86054027-69d0bd80-ba27-11ea-8cc3-d4bcfb97ec79.png)

I'm aware that this entire codepath will soon/eventually die once we no longer use Cairo's toy text API for this backend but even if this is not fixed before that happens it is good to at least have it documented as an issue

**Comment by stuaxo** [comment]
Is it worth using cairos own hit testing with cairo_in_fill or cairo_in_stroke ?

**Comment by ForLoveOfCats** [comment]
Fixed by https://github.com/linebender/piet/pull/389, https://github.com/linebender/piet/pull/425
