### ISSUE TITLE
Recommend using wasm-pack instead of running wasm-bindgen directly

### ISSUE THREAD

**Issue by fitzgen** [linebender/piet#24]
> Make sure that wasm-bindgen is installed. This needs to be the same version of wasm-bindgen used by piet-web.

FYI, we found this to be quite annoying across projects that expect different wasm-bindgen versions, so `wasm-pack` will manage this for you, and all you have to do is `wasm-pack build` and the proper wasm-bindgen CLI is transparently downloaded for you.

Perhaps you ran into the issue of it not supporting workspaces properly? Good news! That is fixed on master and we are cutting a new release today :)

https://github.com/rustwasm/wasm-pack

Cheers!

**Comment by rylev** [comment]
Thanks @fitzgen! I was waiting for the new version, but I'll make this change now that the new version is out.
