### ISSUE TITLE
decide on behaviour when hit testing empty string

### ISSUE THREAD

**Issue by cmyr** [linebender/piet#268]
Ran into this when attempting to update druid: there is currently no good way to determine the cursor position and size when there is no text; and more than that, several platforms currently crash if you call `hit_test_text_position` with position `0` when there is no text.

I can imagine a few approaches:

- we could guarantee that there always exists at least one "line" in a text layout, even if that line is empty; and if required we could fabricate the `LineMetric` object for that line, either by manually resolving the font and using the font metrics, or by having a dummy layout object containing a single space (or something) and using that for the metrics of the empty line.
- we could change `HitTestTextPosition` to include information required to draw the cursor, such as the line height; in the general (non-empty string) case we would just take this from the appropriate `LineMetric`, but in the empty string case we would take it from the font.

I think my preference is for the first of these? I'm trying to think through whether this will cause any obvious problems, and i don't _think_ it does..

**Comment by cmyr** [comment]
Option 3: a `fn default_line_height()` on `TextLayout` that can be used as a fallback in the case that the layout has no lines?

**Comment by raphlinus** [comment]
I don't have very strong feelings about this. The first is fine. It certainly is an interesting edge case!
