### ISSUE TITLE
Implement PartialEq/Hash for Color?

### ISSUE THREAD

**Issue by cmyr** [linebender/piet#290]
Hash is debatable, since we might want to to allow future representations of colors to contain floats, which aren't hashable? PartialEq just feels like an oversight though.

Also: how about `Eq`?

**Comment by raphlinus** [comment]
Eq and Hash are basically the same in terms of what can implement it. This is such a deep set of questions, as, yeah, float seems like a much more natural representation in the case of HDR for the future.

I think I'm fine with PartialEq though.
