### ISSUE TITLE
Ownership / borrowing of Shape

### ISSUE THREAD

**Issue by raphlinus** [linebender/piet#3]
As of #2, the main way of passing a `Shape` through the API is `&impl Shape`. I think that's good, but here are possible ways it could be improved.

It might be desirable to pass in a shape either through moving or borrowing. From the caller's perspective, it's a tiny ergonomics bump, as you'd be able to elide the `&` from `stroke(&Line::(...))`. But perhaps more importantly, an implementer that records into a display list would be able to take ownership, avoiding a clone. 

As a related issue, it *might* also be desirable to add a `Clone` bound, either here or in kurbo. This is not strictly necessary, as this use case might well special-case the shapes it cares about, and just collect the `to_bez_path` iterator results in the general case. The `Clone` bound would in general result in a `Box<dyn Shape>`, which might be useful. Another question: if we add a `Clone` bound, should we also add `Send` so that display lists can be passed across thread boundaries?

One possibility is suggested by this [playground gist](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=1511d90e9ec9c68ff3fa4b549126354f). Another possibility is the [supercow](https://crates.io/crates/supercow) crate.

**Comment by SimonSapin** [comment]
When all methods take `&self`, a somewhat common pattern is `impl<'a, T: Shape> impl Shape for &'a T` so that callers of a `foo(impl Shape)` API can choose to move or pass a borrow. But this prevents adding e.g. `&mut self` default methods to the trait later. (At least to have the `&'a T` impl correctly forward all methods.)

**Comment by raphlinus** [comment]
@SimonSapin I think that's an idea very much worth trying, thanks! On the [Zulip chat](https://xi.zulipchat.com/#narrow/stream/147926-druid/subject/2D.20abstraction.20layer), I brought up the question of whether `Shape` should be immutable, and I'm leaning in that direction.

Presumably you could `impl Shape for Cow` as well?

I'm wondering if this could somehow address the extra clone in `to_bez_path` in the general case, but I'm thinking that's a separate problem, best addressed by waiting for GAT to land.

**Comment by raphlinus** [comment]
Ok, the above-linked PR goes pretty far in solving these problems. It halfway solves the to_bez_path problem in that the impl for `&[PathEl]` doesn't clone, but the impl for `&BezPath` still does. I don't think that's a real problem, the `as_path_slice` method takes care of this in the vast majority of real world cases (all those that store paths as a contiguous slice of `PathEl` internally).
