### ISSUE TITLE
Repeated create_solid_color calls in D2DTextLayout::draw are expensive and unnescessary

### ISSUE THREAD

**Issue by smmalis37** [linebender/piet#303]
https://github.com/linebender/piet/blob/c1d182c31bedaa71694fc8a189cdb7e1bf357e22/piet-direct2d/src/text.rs#L403

The call to create_solid_color on that line gets expensive when you have 700 different labels all painting and recreating the brush every time. It could probably be cached.

**Comment by raphlinus** [comment]
https://crates.io/crates/associative-cache is a good candidate to solve this problem: it's a small zero-dep cache that would help us with all color to brush resolution, not just the default here.

If it was just the default, we could create a black brush on D2DRenderTarget creation and just use it. But Steven's profiling (posted on Zulip) indicates there is a nontrivial cost to brush creation from other sources.
