### ISSUE TITLE
d2d::create_solid_color is expensive to call, but results could likely be cached

### ISSUE THREAD

**Issue by smmalis37** [linebender/piet#304]
Some profiling turned up repeated calls to d2d::create_solid_color (or rather the call to CreateSolidColorBrush inside it) as consuming lots of CPU time. If we assume the user is likely to be using the same colors over and over again (which seems likely to me) then some sort of internal cache for the brushes would likely improve things noticeably.

**Comment by raphlinus** [comment]
See comment in #303, I think the best solution for this is an associative cache.
