### ISSUE TITLE
Add support for gray-scale images

### ISSUE THREAD

**Issue by ruffson** [linebender/piet#313]
## Problem description
Currently the only supported color formats offered by `piet::render_context::ImageFormat` are `Rgb`, `RgbaSeparate` and `RgbaPremul`. It would be nice to have a format representing gray-scale images with 8bit values per pixel.

## Obstacles
Unfortunately it looks like it is not just a matter of adding a new item to `ImageFormat` and the backends, as some backends do not support gray-scale images.
### Linux/GTK backend
By looking at `cairo-rs` it was discovered that `cairo` itself does not support gray-scale image formats. As its [documentation shows](https://www.cairographics.org/manual/cairo-Image-Surfaces.html#cairo-format-t) the only 8bit format `A8` is supposed to be used for alpha values.
### macOS/core graphics
Similary the macOS backend is also not able to deal with grayscale and raises an `unimplemented` error [here](https://github.com/ruffson/piet/blob/bd86db92b18224750eff34a8f19d78e522c3d041/piet-coregraphics/src/lib.rs#L283).

## Workarounds?
If anyone has any suggestion on a way to display gray-scale images with a linux supported backend efficiently, then please share your knowledge here.
I am dealing with quite large images and the only way I have found to display them right now is to save each original pixel value three times in a new vector (I know).

// _Updated with macOS backend findings._

**Comment by ruffson** [comment]
Okay so just a quick update from my side.

I added some very basic code so that an `ImageFormat` for gray-scale images could be used on my [branch here](https://github.com/ruffson/piet/commit/ff53c24e0e0a0e706ec95ef1bbd7f53c93bf3d68).

Then to make this useable with the existing image widget, the `image.rs` in `druid::widget` needs to be modified so that it sets the correct `ImageFormat`.

After doing these things I was able to display my image. However, because the nature of these values being interpreted as alpha values, it is important to use a white background e.g. like this:

```rust
    let mut col = Flex::column();
    col.add_flex_child(
        Image::new(my_image_data.clone())
            .fill_mode(FillStrat::FitWidth)
            .background(Color::WHITE)
            .center(),
        1.0,
    );
```

I asked what the recommended behaviour is on the cairo mailing list and [got the answer](https://lists.cairographics.org/archives/cairo/2020-September/029051.html) that my solution above is the expected way to work with gray-scale images in cairo.

Now I think it is up to the maintainers to either accept this approach or if this needs more work to make alpha formats properly supported instead of slightly abusing the concept.

**Comment by cmyr** [comment]
In the cairo backend, when we draw an image, could we check if it's grayscale and just apply the fill there?

**Comment by ruffson** [comment]
> In the cairo backend, when we draw an image, could we check if it's grayscale and just apply the fill there?

Not sure what you mean, currently in my implementation if a `ImageFormat::GrayScale` was chosen, the cairo backend chooses the `A8` and inverts the pixel color. It is very straight forward, you can take a look [here](https://github.com/linebender/piet/compare/master...ruffson:feature_support_grayscale).

**Comment by cmyr** [comment]
What I mean is that in `RenderContext::draw_image`, if we can determine that the image is grayscale, we can do a white fill in the area of the image before we draw.

**Comment by ruffson** [comment]
> What I mean is that in `RenderContext::draw_image`, if we can determine that the image is grayscale, we can do a white fill in the area of the image before we draw.

Ah good idea! I will look into it. Thank you!

**Comment by ruffson** [comment]
The macOS backend causes an `Unimplemented` error [here](https://github.com/ruffson/piet/blob/bd86db92b18224750eff34a8f19d78e522c3d041/piet-coregraphics/src/lib.rs#L283) when I try to load a grayscale image from my [modified piet image format](https://github.com/linebender/piet/compare/master...ruffson:feature_support_grayscale).

We know how to do this in cairo now (using `A8` with white background), but what is the feasibility on macOS?

**Comment by ruffson** [comment]
I [added a line](https://github.com/ruffson/piet/commit/44429c03bc8f6bd9e015eeb7aea7ae20ad58e479) on my branch that should return a grayscale image, but as I cannot test on macOS myself, I am not sure if this works and if it is enough.

**Comment by cmyr** [comment]
Your fix looks like what I would do as well. If you open a PR I'll be able to test.

**Comment by ruffson** [comment]
> Your fix looks like what I would do as well. If you open a PR I'll be able to test.

You [got it](https://github.com/linebender/piet/pull/350).
