### ISSUE TITLE
Text::Coord v.s. RenderContext::Coord?

### ISSUE THREAD

**Issue by SimonSapin** [linebender/piet#36]
The `Text` and `RenderContext` traits both have `Coord` and `TextLayout` associated types. The former also has a `type Text: Text<TextLayout = Self::TextLayout>;` associated type, with an equality that ensures that the two `TextLayout` types are the same.

But there is no similar constraint to ensure that the two `Coord` types are the same. Is this deliberate?

**Comment by raphlinus** [comment]
I thought about this, and think it's ok. For one, all the text stuff is probably going to be split off into separate modules, so looser coupling is a good thing. For two, right now I'm not seeing a use case where you really need to bridge the two. The associated type exists largely as a carrier for an `Into` to make it convenient to use either `f32` or `f64`, and avoid double conversions when both the caller and callee use the same type.

**Comment by raphlinus** [comment]
Closing this as obsolete, we've basically moved off associated types for coordinates.
