### ISSUE TITLE
[Feature request]: Add an `Image` trait as below

### ISSUE THREAD

**Issue by derekdreery** [linebender/piet#367]
This is a proposal/feature request/RFC: Add the following trait to piet

```rust
pub trait Image {
    fn size(&self) -> Size;
}
```

It would be nice to to have to keep an `ImageBuf` around to know the size of the image.

**Comment by cmyr** [comment]
Can you provide a bit more detail about the friction you're encountering and how you would use this to solve it? I'm open to API additions but would like a better sense of the motivation. :)

**Comment by derekdreery** [comment]
> Can you provide a bit more detail about the friction you're encountering and how you would use this to solve it? I'm open to API additions but would like a better sense of the motivation. :)

For sure :). My motivation is for when using `piet` outside of `druid` (but possibly would be beneficial from inside Druid as well). Currently, if you want to be able to get the size of an image in a cross-platform way, you need to keep the information around from when you built the image. All back-ends provide methods for getting the size of an image after creation, and it might make code cleaner and require less state than otherwise.

**Comment by cmyr** [comment]
Oh to see that I understand:

you're saying we should have an `Image` trait that is conformed to by all of the concrete `Image` types, sort of like the `TextLayout` trait? I do think that this makes sense, and if we're going to do this I would encourage you to make that change now, because we're going to need another release soon.

**Comment by derekdreery** [comment]
I will knock up a PR.
