### ISSUE TITLE
Reexport kurbo types

### ISSUE THREAD

**Issue by msiglreith** [linebender/piet#50]
Reexporting the types defined in kurbo would help to avoid conflicts when users don't specify the same kurbo version in their crates and the one used by piet (e.g two different `Shape` trait versions).

**Comment by raphlinus** [comment]
I think this is probably a good idea. The experience is somewhat fragmented now, some types from piet, some from kurbo, and not intuitively obvious which.

Note that we're also in the middle of rethinking the very base types (Point and Rect) as well. In the case of Point, we want to unify with kurbo Vec2 at the least. We're also considering adopting euclid wholesale; among other things, this would un-unify Vec2 and require categorization of its use into [Point2D](https://docs.rs/euclid/0.19.9/euclid/type.Point2D.html), [Vector2D](https://docs.rs/euclid/0.19.9/euclid/type.Vector2D.html), and [Size2D](https://docs.rs/euclid/0.19.9/euclid/type.Size2D.html). We also have the option of adopting units (device pixels vs px (in CSS terminology) or "point" (in Apple terminology). So it probably makes sense to include this concern in the revamp.

**Comment by cmyr** [comment]
ah, hadn't seen this issue but am working on this. #52 is a start, and I'm going to dig into further improvements.

**Comment by cmyr** [comment]
Happy to consider this closed for now; we re-export `kurbo` itself, and users can get the shapes they need through that.
