### ISSUE TITLE
vertical text support

### ISSUE THREAD

**Issue by ekicyou** [linebender/piet#531]
I'm [experimenting](https://github.com/ekicyou/piet) with piet-direct2d to incorporate vertical text support.

1. Is there room to introduce a [writing-mode](https://developer.mozilla.org/en-US/docs/Web/CSS/writing-mode) API into piet-common? I can't develop anything other than direct2d.

2. In vertical-rl, the origin is on the upper right, is there any discussion? Is it possible to support druid?

3. In vertical, TextLayoutBuilder::max_width is the height specification, is there any discussion?

**Comment by ekicyou** [comment]
We will close because we do not expect official demand for the time being.
I will continue the experiment with a fork.

**Comment by cmyr** [comment]
Indeed, we are not currently looking to add more features to the text API, although vertical text is definitely something we would want to support in an eventual text API for piet-gpu!
