### ISSUE TITLE
More flexible `RenderContext::make_image`

### ISSUE THREAD

**Issue by LucaCiucci** [linebender/piet#553]
I am trying to create a druid widget that renders a 3d scene using WGPU. To do this, I render the scene into a texture, get the data as a `&[u8]` and paint it using piet's [`draw_image`](https://docs.rs/piet/0.6.2/piet/trait.RenderContext.html#tymethod.draw_image).  
Unfortunately, each row in the texture has a stride with an alignment of [`COPY_BYTES_PER_ROW_ALIGNMENT`](https://docs.rs/wgpu/0.15.1/wgpu/constant.COPY_BYTES_PER_ROW_ALIGNMENT.html) bytes so, in order to use it with [`make_image`](https://docs.rs/piet/0.6.2/piet/trait.RenderContext.html#tymethod.make_image), I have to convert it first. This is quite annoying and feels unnecessary.

I think this situation could be common in other situations such as showing images/videos from raw data. Maybe it could be useful to create another function, for example `RenderContext::make_image_flat` that accepts a row pitch, just like [`image::FlatSamples`](https://docs.rs/image/latest/image/flat/struct.FlatSamples.html) that stores the layout information in [`SampleLayout`](https://docs.rs/image/latest/image/flat/struct.SampleLayout.html)

**Comment by xStrom** [comment]
Yes I think this is a reasonable method to add.

On the topic of naming it, is *flat* a common way to describe such a method? It's definitely shorter than an explicit `make_image_with_stride`.

**Comment by LucaCiucci** [comment]
I'm not sure if that's the best name to give this function. This was the first name that came to my mind because I was reading the `FlatSamples` doc.

I don't know many other libraries, afaik Qt does not provide a similar function for images and pixmaps, Skia has [`MakeRasterData`](https://skia-doc.commondatastorage.googleapis.com/doxygen/doxygen/html/classSkImage.html) that is undocumented but an example usage is shown [here](https://fiddle.skia.org/c/@Image_MakeRasterData).

One idea might be to implement `make_image_with_stride` and make the function to accept a `stride` parameter so that the `make_image_flat` can be used in the future for more complex layouts. What do you think?

**Comment by xStrom** [comment]
Yeah that sounds like a decent plan. Let's go with `make_image_with_stride` for now. It's possible to deprecate it later if someone comes up with a better name.

**Comment by LucaCiucci** [comment]
I will try to implement this in a fork if you are ok with that

**Comment by xStrom** [comment]
Yes that sounds good. Then open a pull request here and I can review.
