### ISSUE TITLE
d2d: Use specialized functions for fill/draw

### ISSUE THREAD

**Issue by msiglreith** [linebender/piet#60]
The direct2d backend converts every shape to a path and build a geometry from this.
The API provides specialized functions for most of the shapes which should be prefered.

(TODOs in the code, this issue is mostly for tracking these)

**Comment by raphlinus** [comment]
Agreed. One reason I haven't done this yet is that I also want to upgrade to the 0.3 series of direct2d. That's blocking on upstream. It might be a good idea to get issues filed to track all this work.

**Comment by smmalis37** [comment]
Taking a stab at this.
