### ISSUE TITLE
Migrate to newer direct2d

### ISSUE THREAD

**Issue by raphlinus** [linebender/piet#65]
Currently we're using [direct2d 0.2.0](https://crates.io/crates/direct2d). There are a number of problems with this, including excess debug logging on paths, not being able to set the closed/open status of a path in a single pass when iterating from path elements. I'd like to get us onto the newer 0.3 versions of the direct2d and related crates, but they're still in alpha. I'm wondering what it will take to get those released. It might be worth developing the patch based on alpha so we can shake out any problems.

I've been figuring that we would update the direct2d deps before taking on #60, but if it's going to take a while maybe we should special case `Rect` in particular, as that's the biggest pain point.

@Connicpu who owns the direct2d crates. I might ask for admin privs on those crates so we can move those forward. Also, this is a great "help wanted" issue for someone who wants to dive in.

**Comment by raphlinus** [comment]
A quick note. The new 0.3 alpha crates are missing some methods. In one case, this should force a change in our usage: we should migrate from GenericRenderContext to DeviceContext. The latter is strictly more powerful, and the compatibility requirement is ok (it works on Windows 7 with platform update).

Otherwise, if it has everything we need and works, we can do a release of the directx crates.

It's possible there's something we need that's missing, in which case we should add that.

**Comment by Kethku** [comment]
I'm taking a look at making this change currently as I am running into weird performance issues with the current druid-shell and want to get a better understanding of how things work

**Comment by raphlinus** [comment]
I think @hwchen currently has the token on this - we're going with the raw_d2d branch, as it gives us the most flexibility going forward.

**Comment by Kethku** [comment]
Gotcha. I will hold off then. Is that branch in a semi usable state for me to play around? Or is it in progress?

**Comment by Kethku** [comment]
Nevermind. I see the branch is pretty old. I will hold off until something further happens in this area.

**Comment by hwchen** [comment]
I'm doing some work on it on my own branch, but yes it's pretty far behind master at this point.

**Comment by msiglreith** [comment]
With https://github.com/linebender/piet/pull/111 is this done?

**Comment by raphlinus** [comment]
Yes, closing now, thanks for the reminder.
