### ISSUE TITLE
add #[doc(hidden)] to Null-prefixed types

### ISSUE THREAD

**Issue by cmyr** [linebender/piet#78]
these are for testing and don't need public documentation.

**Comment by raphlinus** [comment]
Is https://github.com/linebender/piet/blob/master/piet/src/lib.rs#L18 not working somehow?

**Comment by cmyr** [comment]
`cargo doc --run` shows a bunch of items.

**Comment by raphlinus** [comment]
Oh, they're showing up in piet-common (but not piet proper) because the `pub use piet::*;` there is not respecting `#[doc(hidden)]`. This seems like perhaps a misfeature in rustdoc. Investigating, it seems that if we add hidden to each type it will be respected, but the blanket one won't.
