### ISSUE TITLE
Scope for font/text handling?

### ISSUE THREAD

**Issue by SimonSapin** [linebender/piet#8]
Reading https://github.com/linebender/piet/pull/5, https://github.com/linebender/piet/pull/7, and https://github.com/linebender/piet/tree/f8bae672/piet-cairo#toy-text-api I’d like to ask: how much text handling do you consider in scope for Piet, @raphlinus? How much do you think should be required of each backend v.s. provided by Piet itself on top of lower-level operations v.s. left to other libraries on top of Piet?

(Also CC @rylev who seems interested.)

I suppose the lowest level (giving the most control to the user) might be rendering a single glyph (or a sequence of positioned glyphs) of a given font. Possibly as a `Shape`, supporting all operations they do.

Beyond this, there’s a lot that seems somewhat outside of the realm of graphics rendering. Line breaking? Bidi? Vertical text? Hit testing? Selection?

Getting from Unicode strings to positioned glyphs is text layout, which is tricky to do correctly for international text. In the open-source world, Pango provides this functionality. http://behdad.org/text/ describes where it fits, and explains that some applications that want a lof of control over text layout may want to do some of it themselves and only use lower-level components such as Harfbuzz. This document is old though, I don’t know how much this is still the case today.

I’ve been thinking about what it would look like to do that in Rust. Some of the pieces are already there:

* https://crates.io/crates/unicode-bidi
* https://crates.io/crates/xi-unicode
* https://crates.io/crates/harfbuzz-sys (it seems that re-implementing Harfbuzz would be a lot more work than the rest of text layout)
* https://crates.io/crates/font-kit

… but I have a hard time figuring out how, on a high level, these pieces fit together. (Sorry if this issue tracker is not quite the place to discuss this.) For example, as far as I understand Harfbuzz operates on one text segment at a time that only uses a single font, direction, and script (writing system). It also maps N Unicode code points to M glyphs in the general case. But how does on split these segments in the first place? If it’s Harfbuzz that maps code points to glyphs but it only deals with a single font at time, where does font selection and fallback happen?

**Comment by raphlinus** [comment]
I'll be writing up more of this. I am starting a project for low level text layout, and just prepared a [roadmap](https://docs.google.com/document/d/1aw41q_izail-p99mN8dHrJeh9tMQ-Pldi54W6m7MHU8/edit?usp=sharing).

**Comment by RazrFalcon** [comment]
>As much as possible, I’d like to use the existing font-kit library as the abstraction to access system fonts. Part of the work will be determining whether there are any missing capabilities or other serious drawbacks in font-kit, and documenting how to address those.

I'm working on it right now. `font-kit` doesn't support font aliases at the moment (like `serif`). They are [hardcoded](https://github.com/pcwalton/font-kit/blob/master/src/source.rs#L32..L54) right now.

Also, there are no way to query a font by a language/script.

In the end, I want something like [QFontDatabase](https://doc.qt.io/qt-5/qfontdatabase.html).

**Comment by SimonSapin** [comment]
The Skribo project now exists, so I think there is no need to keep this issue open.

* https://raphlinus.github.io/rust/skribo/text/2019/02/27/text-layout-kickoff.html
* https://docs.google.com/document/d/1aw41q_izail-p99mN8dHrJeh9tMQ-Pldi54W6m7MHU8/edit
* https://github.com/linebender/skribo
