### ISSUE TITLE
Make piet-coregraphics real

### ISSUE THREAD

**Issue by raphlinus** [linebender/piet#86]
#4 has a work in progress CoreGraphics backend. I think there's a good case to be made to bring this up to usable state.

* After a period of fluidity, I think the piet API is more stable. One of the main things that still needs work is richer text, and I think there's use in considering both CoreText and DirectWrite at roughly the same time.

* The Cairo dependency is a papercut for macOS build, test, and deployment.

* The Cairo "toy text API" is the source of degraded capabilities, in particular fallback fonts.

* A skribo-based text module is the future path for the Cairo backend, but this won't be ready for quite some time.

**Comment by futurepaul** [comment]
I rebased #4 and [got it compiling with the 0.0.6 changes](https://github.com/futurepaul/piet/tree/cg). Haven't looked closely enough to see how much actual work is needed to make it functional or "good".
